feat: As json flag allows for more native type usage
memphisdev/memphis-functions.js pull request #5
Opened 2023-12-09 07:59 UTC by John-Memphis

2023-12-10 13:52 UTC, idanasulinmemphis requested changes

2023-12-10 13:52 UTC, idanasulinmemphis commented on README.md
> +    return await memphis.createFunction(event, eventHandler, as_json = true);
as_json -> asJson

2023-12-10 13:52 UTC, idanasulinmemphis commented on README.md
> +        processedMessage: Buffer.from(JSON.stringify(payload), 'utf-8'),
in case it is a json, the user should not convert it to bytes as well we can do it for him

2023-12-11 08:08 UTC, John-Memphis commented on README.md
> +        processedMessage: Buffer.from(JSON.stringify(payload), 'utf-8'),
The readme was wrong, I was converting it already in the actual function. Good catch :)

2023-12-11 08:49 UTC, idanasulin2706 approved these changes

2023-12-11 08:49 UTC, merged